/// <reference path="External/jquery/jquery-2.0.3.js" />
/// <reference path="External/jqueryValidate/jquery.validate.js" />
/// <reference path="External/knockout/knockout-3.0.0.js" />
/// <reference path="External/bootstrap/bootstrap.js" />
/// <reference path="External/bootstrap/bootbox.js" />
/// <reference path="External/jHtmlArea/jHtmlArea-0.7.5.js" />
/// <reference path="External/moment/moment.js
/// <reference path="Custom/utils.js" />
/// <reference path="Custom/logo.js" />
/// <reference path="Custom/card.js" />
/// <reference path="Custom/login.js" />
/// <reference path="Custom/offlinestorage.js" />
/// <reference path="Custom/Sections/decksList.js" />
/// <reference path="Custom/Sections/editDeck.js" />