// <auto-generated />
namespace MegaMemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _2014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2014));
        
        string IMigrationMetadata.Id
        {
            get { return "201401031245212_2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
